language: node_js
services:
  - mysql
node_js:
  - "6.0.0"
before_script:
  - npm install -g jasmine
script: npm test
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS testdb;" -uroot
  - mysql -e "CREATE TABLE testdb.tbl_person (id int(11) NOT NULL AUTO_INCREMENT, fullName varchar(45) NOT NULL,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1;" -uroot